<a href="https://colab.research.google.com/github/4ci1ab/NH704F/blob/main/cyl_cart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import os
import pandas as pd

import math as mt
from tabulate import tabulate as tb
from IPython.display import display

import scipy.constants as sc
from scipy import constants

In [ ]:
def cyl_cart(cyl):
  x = cyl[0] * mt.sin(cyl[1]) * mt.cos(cyl[2])
  y = cyl[0] * mt.sin(cyl[1]) * mt.sin(cyl[2])
  z = cyl[0] * mt.cos(cyl[1])

  print(np.array([x,y,z]))# Store this value???? to refrence.


In [ ]:
re3 = np.array([1, 0.9, 0.1])

re1 = np.array([0.9, 0.25, 0.6])

re2 = np.array([0.632, 0.33, 0.19054])

re0 = np.array([0.03, 0.765, 0.45])

re7 = np.array([-0.03, -0.765, -0.45])

In [ ]:
cyl_cart(re3)
cyl_cart(re1)
cyl_cart(re2)
cyl_cart(re0)

[0.77941354 0.0782022  0.62160997]
[0.18377217 0.12572531 0.87202118]
[0.20108883 0.03878599 0.59789876]
[0.01870779 0.00903689 0.02164147]


In [ ]:
def rho(s):
  return 1*s

In [ ]:
def E_fd(s):
  (rho(s))/(2(mt.pi)*(sc.epsilon_0)*(s))

<>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<ipython-input-14-c5f9e5faf73c>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  (rho(s))/(2(mt.pi)*(sc.epsilon_0)*(s))


In [ ]:
def PhiF(s):
  phigs = - sp.integrate(E_fd(s),s)

In [ ]:
def renplt(n,x,y):
  plt.plot(n)
  plt.xlabel(x)
  plt.ylabel(y)
  plt.show()